FORMAT: 1A

# Identity
Collection of API's used within Identity


    Response Codes
        code
            200 Success
            400 Bad Request
            404 Not Found
            500 Internal Server Error
        idcode
            2000 Success
            4000 Bad Request
            4040 Not Found
            5000 Internal Server Error

# Group User Resources

## Match User [/matchuser]
The Match API is an interface between Sainsburys missions (Entertainment, TU Clothing, Bank...).
The aim of this API is to try to match the input parameters to user attributes within the one or
more missions at Sainsburys.

### Match user based on supplied attributes [POST]

Get a match for user attributes response.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "mission"   :   "ENTS",
                "userid"    :   "s.shah@email.com",
                "nectar"    :   "1234567890",
                "firstname" :   "syed",
                "lastname"  :   "shah"
            }

+ Response 200 (application/json)

    + Body
    
            {
                "mission": "ENTS",
                "matchedmissionaccounts": {
                    {
                        "lastloggedin": 1457439635,
                        "missionUserId": "s.shah@email.com",
                        "missionUserUUID": "MissionSpecificId",
                        "loa": 10
                    }
                },
                "message": "success",
                "ResponseCodes:": {
                    "code": "200",
                    "idcode": "2000"
                }
            }
            
## Verify User [/verify]
The Verify API is an interface between Sainsburys missions (Entertainment, TU Clothing, Bank...).
The aim of this API is to try to verify a user within a specific mission at Sainsburys.

### Verify user against specified mission [GET]
Verify user credentials attributes response.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "mission"   :   "ENTS",
                "id"        :   "id",
                "userid"    :   "s.shah@email.com",
                "password"  :   "e807f1fcf82d132f9bb018ca6738a19f"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "mission": "ENTS",
                "userid"    :   "s.shah@email.com",
                "message": "200"
            }
            
## User Merge [/mergeuser]
The Merge API is an interface between Sainsburys missions (Entertainment, TU Clothing, Bank...).
The aim of this API is to try to merge other Sainsburys accounts into the identity My Account.

### Merge accounts into the Identity My Account [POST]
Get a response for the Merging of user attributes.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "mission"   :   "ENTS",
                "UUID"      :   "6c59c99d-2c6b-4d65-adf0-7121da1ed76b",
                "userid"    :   "s.shah@email.com"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "mission" : "ENTS",
                "message" : "success",
                "code"    : "200",
                "id_code" : "2000"
            }

# Group Update Resources

## Update Nectar [/updateNectar]
The Update Nectar API is a REST API for adding multiple nectar card number assoiciated with a User.

### Add multiple Nectar cards associated with user [POST]
Get a response for the Updating of user attribute nectarCard.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "UUID"              : "6c59c99d-2c6b-4d65-adf0-7121da1ed76b",
                "nectarcard_number" : "0123456789"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "message" : "success",
                "code"    : "200",
                "id_code" : "2000"
            }
            
## Update Mobile [/updateMobile]
The Update Mobile List API is a REST API for adding multiple mobile numbers to a mobile list assoiciated with a User.

### Add multiple mobile numbers to a mobile list associated with a user [POST]
Get a response for the Updating of user attribute mobile.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "uid"    : "shahs7784",
                "mobile" : "07123456789"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "message" : "success",
                "code"    : "200",
                "id_code" : "2000"
            }

## Password Recovery [/passwordrecovery]
The Password Recovery API will allow a user to initiate a password recovery for a mission via Identity.

### Recover Password [GET]
Get a response from a mission that a password recovery was initiated.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "mission" : "ENTS",
                "user_id" : "s.shah@email.com"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "mission" : "ENTS",
                "message" : "success",
                "code"    : "200",
                "id_code" : "2000"
            }

## Available Missions [/availableMissions]
The Avaialble Missions API is a REST API for getting the currently available missions.

### Get available missions [GET]
Get a response for the currently available missions.

+ Request (application/json)
    + Headers
    
            Accept: application/json

+ Response 200 (application/json)

    + Body
    
            {
                "code"              : "200",
                "availableMissions" : {
                    "mission": [
                        {"id": "GOL", "name": "Groceries"},
                        {"id": "ENTS", "name": "Entertainment"},
                        {"id": "TU", "name": "Clothing"},
                        {"id": "MOBILE", "name": "Mobile"},
                        {"id": "SMARTSHOP", "name": "Smartshop"},
                        {"id": "BANK", "name": "Bank"}
                    ]
                }
            }

# Group Payment Card Resources

## Add Card [/registercard]
The add card service allows for the adding of a payment card to the users MyAccount profile.
The API acts as a service end point for missions withing Sainsburys and will handle all remote calls to TLG.

### Add Payment Card [POST]
Get an autorisation response for adding card.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "amount"      : "1",
                "description" : "Adding A New Payment Card",
                "resultpage"  : "http://www.sainsburys.com"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "responsecodes": {
                    "idcode": "2000",
                    "code": "200"
                },
                "message": "success",
                "transno": "8542746272",
                "transref": "8baf67b9-7d83-413e-baa6-7120d29b3e50",
                "url": "https://etestws1.secure-payment-processing.com/SOLVESAIN1/pages/paypage.jsf?transref\u003d8baf67b9-7d83-413e-baa6-7120d29b3e50\u0026store\u003d040006"
            }
            
## Verify Card [/verifycard]

### Verify Payment Card [POST]

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "transno"  : "123456789",
                "transRef" : "ff5343b2-38e0-403b-8fed-f0dc4d628b2b"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "uniqueid" : "d7017ab0-f22a-4cb0-b657-f648ff2e1877",
                "result"   : "success"
            }

# Group Bumblebee Nectar Card Resources

## Get card info [/get-nectarcard-info]
Checks the linking status and points balance of a Nectarcard.

### Get nectar card info [POST]
Checks the linking status and points balance of a Nectarcard.

    Request Attributes
        "nectar_number" : Nectarcard number

    Response Attributes
        "user_email_address"  : the email address stored against the given Nectarcard number.
        "linked_status" : One of
            "NOT" (not linked)
            "LKD" (linked)
            "UNL" (unlinked when previously linked)
            "CLD" (linking process cancelled while the user was trying to link the card number)
        "points_balance"      : number of points currently on the card
        "balance_age_seconds" : time in seconds since the balance was last updated from the live balance stored by the Aimia Nectar service.

    Response Codes
        200 Success
        422 Unprocessable Entity - when the request is malformed.
        500 Internal Server Error
        
+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "nectar_number"      :   "68497459019"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "user_email_address"  : "test001.bumblebee@sainsburysentertainment.co.uk",
                "linked_status"       : "LKD",
                "points_balance"      : "2500",
                "balance_age_seconds" : 3602627
            }

## Link card [/link-nectarcard]
Checks the linking status and points balance of a Nectarcard.

### Linking a card [POST]
Initiates the card linking process, to link a Nectarcard to a user.

    Request Attributes
        "nectar_number"      : Nectarcard number
        "user_email_address" : The user's email address
        "return_url"         : The URL to redirect the browser to, when the linking process eventually succeeds

    Response Attributes
        user_email_address : The email address provided in the request.
        uuid               : A UUID used by Bumblebee in some URLs
        linking_url        : The URL to redirect the browser to at the end of the linking process

    Response Codes
        200 Success
        422 Unprocessable Entity - when the request is malformed.
        500 Internal Server Error
        
+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "nectar_number"      : "68497459019",
                "user_email_address" : "test001.bumblebee@sainsburysentertainment.co.uk",
                "return_url"         : "http://aservice.sainsburys.co.uk/nectarlinked"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "user_email_address" : "test001.bumblebee@sainsburysentertainment.co.uk",
                "uuid"               : "dfb299ee-0b91-4314-8e2a-109ec2e8711e",
                "linking_url"        : "https://dev-nectar-linking.sainsburys.co.uk/link/nectar/dfb299ee-0b91-4314-8e2a-109ec2e8711e"
            }
        
## Unlink card [/unlink-nectarcard]
Initiates the card unlinking process, to remove the link between the Nectarcard and a user.

### Unlink Card [POST]
Request Attributes
    "nectar_number" : Nectarcard number

Response Attributes
    user_email_address : the email address stored against the given Nectarcard number.
    status             : one of "ok" or "fail_account". This is informational only.
                         The status string 'account_fail' means that that there was an issue on the Aimia account side, and the actual response status code is 200/OK rather than an error response.

+ Request (application/json)
    + Headers
    
            Accept: application/json

    + Body
    
            {
                "nectar_number" : "68497459019"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "user_email_address" : "test001.bumblebee@sainsburysentertainment.co.uk",
                "status"             : "fail_account"
            }