FORMAT: 1A

# HelloWorld

Hello World is a simple API allowing consumers to say hello!

## World Collection [/worlds]

### List All Worlds [GET]
Here is the status 200 response.

+ Response 200 (application/json)

        [
            {
                "worlds": [
                    {
                        "world": "Earth"
                    }, {
                        "world": "Jupiter"
                    }, {
                        "world": "Mars"
                    }
                ]
            }
        ]

+ Response 404 (text/plain)

        Requested resourse not found.
    
+ Response 500 (text/plain)

        Server error.
        

### Create a New World [POST]

You may create your own world using this action. It takes a JSON
object containing a world.

+ Request (application/json)

        {
            "world": "Saturn"
        }

+ Response 201 (application/json)

    + Headers

            Location: /worlds

    + Body

            {
                "worlds": [
                    {
                        "world": "Earth"
                    }, {
                        "world": "Jupiter"
                    }, {
                        "world": "Mars"
                    }, {
                        "world": "Saturn"
                    }
                ]
            }